### ISSUE TITLE
[FeatureRequest] Add EventGrid source option for blob_trigger

### ISSUE THREAD

**Issue by jonathan-conder-sm** [Azure/azure-functions-python-library#197]
This is already documented [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger#decorators):

> - source: Sets the source of the triggering event. Use EventGrid for an Event Grid-based blob trigger, which provides much lower latency. The default is LogsAndContainerScan, which uses the standard polling mechanism to detect changes in the container.

But [blob_trigger](https://github.com/Azure/azure-functions-python-library/blob/ded84af5910aa2333568c144f8349502e4d6c338/azure/functions/decorators/function_app.py#L991) has no such argument and [BlobTrigger](https://github.com/Azure/azure-functions-python-library/blob/ded84af5910aa2333568c144f8349502e4d6c338/azure/functions/decorators/blob.py#L10) ignores the `kwargs`.

**Comment by YunchuWang** [comment]
a pr is out for https://github.com/Azure/azure-functions-python-library/issues/197.

**Comment by YunchuWang** [comment]
@jonathan-conder-sm thanks for reporting, i am able to use kwargs to specify source as EventGrid and my app is triggered properly by EventGrid blob events. 
![image](https://github.com/Azure/azure-functions-python-library/assets/12449837/d652c4dd-e4bb-4cfe-8182-f902a80990af)

![image](https://github.com/Azure/azure-functions-python-library/assets/12449837/290ad25a-49d5-480d-8dee-8f63df7cd626)

Please ensure you follow every step defined in https://learn.microsoft.com/en-us/azure/azure-functions/functions-event-grid-blob-trigger?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-python to get it set up. 

we would add native source support for it. thanks for bring that up

**Comment by xanecs** [comment]
@YunchuWang I don't think your example is working correctly. In the invocation details (your 2nd screenshot on the right) it is mentioned, that the blob trigger is still using LogsAndContainerScan instead of EventGrid.
Incidentally, I am also trying to set this up right now and am unable to.
Using your code I cannot create the Event subscription because the webhook returns a 404. Presumably, because it does not actually register an EventGrid blob trigger, as the kwarg is ignored.

Even if I am wrong about this, and EventGrid Blob Triggers are supported after all, I would highly appreciate it, if the documentation you linked could be updated with a working example for the python v2 programming model.
