### ISSUE TITLE
Question: Azure Functions Python library Development Cycle

### ISSUE THREAD

**Issue by marcheseV** [Azure/azure-functions-python-library#72]
Hi,

I've a quick question regarding the development cycle of the Azure Functions Python library and it's integration with other Azure services like Azure Functions App: In the documentation for Python developers using Azure Functions (link [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#preinstalled-libraries)) it mentions that each worker includes a new version of Azure Functions Python library, but that the runtime library version is fixed by **Azure**, and it _can't be overridden_. The current version is 1.3.0 on Functions App, but the latest release of the library is 1.3.1 with some very useful features. So, my question is:

When will the latest release of the Azure Functions Python library be added to the Azure Functions App worker nodes? 

Thanks,
Vinny

**Comment by vrdmr** [comment]
Hi @marcheseV, Apologies for the delay.

The worker includes the [library version reference](https://github.com/Azure/azure-functions-python-worker/blob/dev/setup.py#L298) hard-coded, and a similar pattern is used for the worker to be included in the functions-host. You can find the [release notes](https://github.com/Azure/azure-functions-host/releases) of functions host to see the worker/library version is included in the newest release.

> When will the latest release of the Azure Functions Python library be added to the Azure Functions App worker nodes?

There is currently a deployment in progress for [1.1.6](https://github.com/Azure/azure-functions-python-worker/releases/tag/1.1.6) with library version [1.4.0](https://github.com/Azure/azure-functions-python-library/releases/tag/1.4.0). Once it is completed, I'll update this thread.

We tend to release at least once a month, but we depend on the release schedule of the host and we have seen it delay due to regressions.

Please let me know if you have more questions.
